In [1]:
grid = [
    [7, 8, 0, 4, 0, 0, 1, 0, 0],
    [6, 0, 0, 0, 7, 5, 0, 0, 9],
    [0, 0, 0, 6, 0, 1, 0, 7, 8],
    [0, 0, 7, 0, 4, 0, 2, 6, 0],
    [0, 0, 1, 0, 0, 0, 9, 3, 0],
    [0, 0, 4, 0, 6, 0, 0, 0, 5],
    [0, 7, 0, 3, 0, 0, 0, 1, 2],
    [1, 2, 0, 0, 0, 7, 4, 0, 0],
    [0, 4, 0, 0, 0, 6, 0, 0, 0]
]

In [2]:
print(grid)

[[7, 8, 0, 4, 0, 0, 1, 0, 0], [6, 0, 0, 0, 7, 5, 0, 0, 9], [0, 0, 0, 6, 0, 1, 0, 7, 8], [0, 0, 7, 0, 4, 0, 2, 6, 0], [0, 0, 1, 0, 0, 0, 9, 3, 0], [0, 0, 4, 0, 6, 0, 0, 0, 5], [0, 7, 0, 3, 0, 0, 0, 1, 2], [1, 2, 0, 0, 0, 7, 4, 0, 0], [0, 4, 0, 0, 0, 6, 0, 0, 0]]


In [3]:
import numpy as np
print(np.matrix(grid))

[[7 8 0 4 0 0 1 0 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 0 0 9 3 0]
 [0 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 0 0 0 6 0 0 0]]


In [4]:
def possible(y, x, n):
    global grid
    for i in range(9):
        if grid[y][i]==n:
            return False
        if grid[i][x]==n:
            return False
            
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j]==n:
                return False
    return True

In [5]:
possible(0,2,5)

True

In [6]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x]==0:
                for n in range(1,10):
                    if possible(y, x, n):
                        grid[y][x]=n
                        solve()
                        grid[y][x]=0 
                return
    print(np.matrix(grid))
    input("More?\n")

In [7]:
solve()

[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 3 9 6 2 1 5 7 8]
 [3 5 7 9 4 8 2 6 1]
 [8 6 1 7 5 2 9 3 4]
 [2 9 4 1 6 3 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [9 4 3 2 1 6 8 5 7]]
[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 3 9 6 2 1 5 7 8]
 [8 5 7 9 4 3 2 6 1]
 [2 6 1 7 5 8 9 3 4]
 [3 9 4 1 6 2 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [9 4 3 2 1 6 8 5 7]]
[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 9 3 6 2 1 5 7 8]
 [8 5 7 9 4 3 2 6 1]
 [2 6 1 7 5 8 9 3 4]
 [9 3 4 1 6 2 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [3 4 9 2 1 6 8 5 7]]
